### ISSUE TITLE
Run on real windows PC machine

### ISSUE THREAD

**Issue by azzamsa** [BiznetGIO/digs#1]
Should it works on "real" windows machine?

**Comment by azzamsa** [comment]
If you see it on the actions tab. digs built and tested on several machines[1].

We also managed to run it on a "real" Windows machine.
Kudos to @HuseinA who own the machine.

windows-gnu:


![image](https://user-images.githubusercontent.com/17734314/108559763-5499fd80-732e-11eb-9397-0a9de06820d4.png)

windows-msvc:

![image](https://user-images.githubusercontent.com/17734314/108559815-6aa7be00-732e-11eb-991d-932f63f7104f.png)


---

[1]:

![image](https://user-images.githubusercontent.com/17734314/108559588-143a7f80-732e-11eb-8bec-954703775f4a.png)

**Comment by sergeevabc** [comment]
My ISP blocks 53 port for queries meant for third-party DNS resolvers, so one has to use alternative ports (e.g. 77.88.8.8:1253, 91.239.100.100:5353), but `digs.exe` doesn't seem to have this functionality at the moment. Consider adding optional `port` param in `digs.toml`, or even using address with port as is (`address:port`).

**Comment by azzamsa** [comment]
> My ISP blocks 53 port for queries meant for third-party DNS resolvers, so one has to use alternative ports (e.g. 77.88.8.8:1253, 91.239.100.100:5353), but `digs.exe` doesn't seem to have this functionality at the moment. Consider adding optional `port` param in `digs.toml`, or even using address with port as is (`address:port`).

Would you like to open a new issue for this?
