### ISSUE TITLE
Alternative port for DNS queries

### ISSUE THREAD

**Issue by sergeevabc** [BiznetGIO/digs#21]
My ISP blocks 53 port for queries meant for third-party DNS resolvers, so one has to use alternative ports (e.g. 77.88.8.8:1253), but `digs.exe` doesn't seem to have this functionality at the moment. Consider adding optional `port` param in `digs.toml`, or even using address with port as is (`address:port`).

_Originally posted by @sergeevabc in https://github.com/BiznetGIO/digs/issues/1#issuecomment-1868952901_

**Comment by azzamsa** [comment]
Can you try this branch https://github.com/BiznetGIO/digs/tree/custom-port?

To install, read https://github.com/BiznetGIO/digs?tab=readme-ov-file#development

**Comment by sergeevabc** [comment]
Sorry, I'm an ordinary Windows 7 x64 user, who feels more confident testing compiled binaries than compiling them myself without proper knowledge of those tools.

**Comment by azzamsa** [comment]
Please try the 0.4.0 https://crates.io/crates/digs/0.4.0

**Comment by sergeevabc** [comment]
I'd be happy to try, but I don't see a binary, @azzamsa.
https://github.com/BiznetGIO/digs/releases/tag/v0.4.0 has source.zip, not .exe

**Comment by azzamsa** [comment]
Can you try this https://github.com/BiznetGIO/digs/releases/tag/v0.4.0?

**Comment by sergeevabc** [comment]
It works as expected, thank you, @azzamsa.
